# Generated by Django 6.1 on 2026-08-22 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(default="OI", max_length=10)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="employees.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_id", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("job_position", models.CharField(default="Employee", max_length=150)),
                ("location", models.CharField(default="Headquarters", max_length=150)),
                ("date_of_joining", models.DateField()),
                ("joining_serial", models.IntegerField(default=1)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="employee_photos/"
                    ),
                ),
                (
                    "status_indicator",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present (Green)"),
                            ("ON_LEAVE", "On Leave (Airplane)"),
                            ("ABSENT", "Absent (Yellow)"),
                        ],
                        default="ABSENT",
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("residing_address", models.TextField(blank=True, null=True)),
                ("nationality", models.CharField(default="Indian", max_length=100)),
                (
                    "personal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("gender", models.CharField(default="Male", max_length=20)),
                ("marital_status", models.CharField(default="Single", max_length=20)),
                (
                    "about",
                    models.TextField(
                        blank=True,
                        default="Passionate professional dedicated to delivering excellence.",
                    ),
                ),
                (
                    "job_love_reason",
                    models.TextField(
                        blank=True,
                        default="Collaborative environment and impactful, challenging work.",
                    ),
                ),
                (
                    "interests_hobbies",
                    models.TextField(
                        blank=True,
                        default="Reading, traveling, and continuous learning.",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="employees.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="employees.department",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                ("issue_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("bank_name", models.CharField(max_length=150)),
                ("ifsc_code", models.CharField(max_length=30)),
                ("pan_number", models.CharField(max_length=30)),
                ("uan_number", models.CharField(blank=True, max_length=30, null=True)),
                ("employee_code", models.CharField(max_length=50)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("EDUCATION", "Education"),
                            ("EXPERIENCE", "Experience"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_items",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_wage",
                    models.DecimalField(
                        decimal_places=2, default=50000.0, max_digits=12
                    ),
                ),
                ("working_days_per_week", models.IntegerField(default=5)),
                (
                    "break_time_hrs",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "working_schedule",
                    models.CharField(default="Standard (40 hrs/week)", max_length=100),
                ),
                ("wage_type", models.CharField(default="Monthly", max_length=50)),
                (
                    "basic_salary_pct",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "hra_pct",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "standard_allowance_pct",
                    models.DecimalField(decimal_places=2, default=16.67, max_digits=5),
                ),
                (
                    "performance_bonus_pct",
                    models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
                ),
                (
                    "lta_pct",
                    models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
                ),
                (
                    "employee_pf_pct",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                (
                    "employer_pf_pct",
                    models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
                ),
                (
                    "professional_tax",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_info",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.CharField(default="Intermediate", max_length=50)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
